//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4uTc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers_Materials
    {
        public int id { get; set; }
        public int IDMaterial { get; set; }
        public int IDSupplier { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
